title: WordRipple Theme Documentation
description: Installation, setup, customization, and support documentation for WordRipple for Shopify.
url: https://urban-canvas.github.io
baseurl: /wordripple-theme-documentation
theme: jekyll-theme-cayman
show_downloads: false
markdown: kramdown
lang: en
