title: Vellum Theme Documentation
description: Installation, setup, customization, and support documentation for Vellum for Shopify.
url: https://urban-canvas.github.io
baseurl: /vellum-theme-documentation
theme: jekyll-theme-cayman
show_downloads: false
markdown: kramdown
lang: en
